export const DRIVER_DEFAULT_ALTITUDE_METERS = 20;
export const DRIVER_REACHED_HORIZONTAL_METERS = 10;
export const DRIVER_REACHED_VERTICAL_METERS = 8;
export const DRIVER_CAMERA_HEIGHT_OFFSET_METERS = 400;
export const DRIVER_CAMERA_TOPDOWN_PITCH_DEGREES = -90;
