export const MISSION_DEFAULT_ALTITUDE_METERS = 100;
export const MISSION_MIN_WAYPOINT_COUNT = 2;
export const MISSION_NUDGE_XY_METERS = 5;
export const MISSION_NUDGE_Z_METERS = 2;
export const MISSION_MIN_ALTITUDE_METERS = 0;

export const MISSION_GIZMO_AXIS_LENGTH_METERS = 120;
export const MISSION_GIZMO_AXIS_LINE_WIDTH = 5;
export const MISSION_GIZMO_AXIS_TIP_SIZE = 10;
